export const SET_SOURCES_REQUESTED = "SET_SOURCES_REQUESTED";

export const SET_SOURCES_SUCCESS = "SET_SOURCES_SUCCESS";

export const SET_SOURCES_FAILURE = "SET_SOURCES_FAILURE";

export const SET_SOURCE_REQUESTED = "SET_SOURCE_REQUESTED";

export const SET_SOURCE_SUCCESS = "SET_SOURCE_SUCCESS";

export const SET_SOURCE_FAILURE = "SET_SOURCE_FAILURE";

export const SET_FAVORITES = "SET_FAVORITES";
